{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dockerproxy-webhook.serviceAccountName" . }}
  labels:
    {{- include "dockerproxy-webhook.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dockerproxy-webhook
subjects:
  - kind: ServiceAccount
    name: dockerproxy-webhook
    # replace with namespace where provisioner is deployed
    namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
